dataset:
  min_images_per_class: 60
  download_images_per_class: 140
  random_state: 42
  min_width: 160
  min_height: 160

  split:
    train: 0.75
    val: 0.15
    test: 0.10

  classes:
    - imran_khan
    - nawaz_sharif
    - shehbaz_sharif
    - maryam_nawaz
    - bilawal_bhutto_zardari
    - asif_ali_zardari
    - maulana_fazlur_rehman
    - altaf_hussain
    - siraj_ul_haq
    - hamza_shahbaz
    - sherry_rehman
    - fawad_chaudhry
    - chaudhry_nisar_ali_khan
    - khurram_dastgir_khan
    - tariq_fazal_chaudhry
    - maryam_aurangzeb

  class_queries:
    imran_khan: "Imran Khan face portrait"
    nawaz_sharif: "Nawaz Sharif face portrait"
    shehbaz_sharif: "Shehbaz Sharif face portrait"
    maryam_nawaz: "Maryam Nawaz face portrait"
    bilawal_bhutto_zardari: "Bilawal Bhutto Zardari face portrait"
    asif_ali_zardari: "Asif Ali Zardari face portrait"
    maulana_fazlur_rehman: "Maulana Fazlur Rehman face portrait"
    altaf_hussain: "Altaf Hussain face portrait"
    siraj_ul_haq: "Siraj ul Haq face portrait"
    hamza_shahbaz: "Hamza Shahbaz face portrait"
    sherry_rehman: "Sherry Rehman face portrait"
    fawad_chaudhry: "Fawad Chaudhry face portrait"
    chaudhry_nisar_ali_khan: "Chaudhry Nisar Ali Khan face portrait"
    khurram_dastgir_khan: "Khurram Dastgir Khan face portrait"
    tariq_fazal_chaudhry: "Tariq Fazal Chaudhry face portrait"
    maryam_aurangzeb: "Maryam Aurangzeb face portrait"
